**Data science assignment -1**





In [12]:
#1.Generate a tuple from the set ["aman", "222", 777, 400.4]
set = ["aman","222",777,400.4]
tup = tuple(set)
print(tup)

('aman', '222', 777, 400.4)


In [13]:
#2.Create a dictionary of your basic data: (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.
dict1 = {"Roll Number": "CB.EN.U4CSE20252","First Name": "Sai Ramya","Last Name": "Illuri","DOB": "02-12-2002"}
print(dict1)


{'Roll Number': 'CB.EN.U4CSE20252', 'First Name': 'Sai Ramya', 'Last Name': 'Illuri', 'DOB': '02-12-2002'}


In [11]:
#3.Use rand function to generate a 2-dimensional random array with seed.
from numpy import random
arr = random.randint(0,1,size = (2,2))
print(arr)

[[0 0]
 [0 0]]


In [14]:
#4.Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)
import numpy as np
x=np.random.uniform(0.0,1.0)
print(x)
print(abs(-1234))

0.9009719456483994
1234


In [15]:
#5.Return a random integer N such that 20 <= N <= 90. 
x=np.random.randint(20,91)
print(x)

50


In [25]:
#6.Given a population or set[11, 12, 13,14, 15]
#Return a 3 length list of unique elements without replacement.
set1 = set([11,12,13,14,15])
set2 = random.choices(list(set1), k=3)
print(set2)

TypeError: ignored

In [ ]:
import random
Set1 = set([11, 12, 13, 14, 15])
UpdatedList = random.choices(list(Set1), k = 3)
print(UpdatedList)
set2 = random.choice(list(Set1))
print(set2)

In [ ]:
#7.Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.
import os
os.getcwd()
os.chdir(r"/content/sample_data")
os.mkdir('document1')
os.chdir('document1')
f = open('document_1.txt','w+')
f.write('The King is Dead, Long Live The King')
f.seek(0)
print(f.read())
f.close()

The King is Dead, Long Live The King


In [19]:
#8.Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue. 
#a)
def eligible(z):
  if(z>=18):
    print("Eligible to vote")
  else:
    print("Not Eligible to vote")
eligible(20)
#b)
for i in range(10):
  print(i)
#c)
x=0
while(x<10):
  x+=1
  if x==5:
    continue
  if x==8:
    break
  print(x)

Eligible to vote
0
1
2
3
4
5
6
7
8
9
1
2
3
4
6
7


In [ ]:
#9.	Given a string "The King is Dead, Long Live The King" 
#Print the complete string
#Print first character of the string
#Print characters starting from 3rd to 5th
#Print string starting from 3rd character
#Split the words

string = 'The King is Dead, Long Live The King'
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
str = string.split()
print(str)

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [24]:
#10.An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elementsimport numpy as np
list2=[1,4,5,8]
arr=np.array(list2)
print("The first and second element of arr",arr[0],arr[1]) 

The first and second element of arr 1 4


In [26]:
#11.Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#12.Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
print("Second Row",arr[1:][:])
print("Second Col",arr[1:,1])
print("Length of the array :",len(arr))

Second Row [[0 0]]
Second Col [0]
Length of the array : 2


In [ ]:
#13.Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the arraylist3=[]
for i in range(10):
  list3.append(np.random.randint(0,100))
oned=np.array(list3)
print("1D array :",oned)
twod=oned.reshape(5,2)
print("2D array :\n",twod)
print("Transpose :\n",twod.T)

1D array : [56  9 64 38 52 38 23 55 69 82]
2D array :
 [[56  9]
 [64 38]
 [52 38]
 [23 55]
 [69 82]]
Transpose :
 [[56 64 52 23 69]
 [ 9 38 38 55 82]]


In [ ]:
#14.Create an array from a list of 1,2 and 3.
l1=[1,2,3]
l2=[1,2,3]
l3=[1,2,3]
newarr=np.array([l1,l2,l3])
print(newarr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#15.Fill an array [1,2,3] with a single value [9,9,9]. 
arr=np.array([1,2,3])
for i in range(len(arr)):
  arr[i]=9
print(arr)

[9 9 9]


In [ ]:
#16.Sum the elements of array [2,4,5].
arr=np.array([2,4,5])
sum=0
for i in arr:
  sum+=i
print(sum)

11


In [ ]:
#17.Give the products of array [77,74,75]
arr=np.array([77,74,75])
prod=1
for i in arr:
  prod*=i
print(prod)

427350


In [ ]:
#18.Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.median(arr))
print(np.argmax(arr))
print(np.std(arr))

12.461538461538462
367.32544378698225
56
1
1
2.0
12
19.165736192147232


In [ ]:
#19.Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
arr=np.array([1, 1, 7, 5, 5, 5, 4])
temp=np.array(np.unique(arr))
temp.sort()
print(temp)

[1 4 5 7]


In [ ]:
#20.Find dot product of two arrays [1, 2, 3]and [0, 1, 1].
x=np.array([1,2,3])
y=np.array([0,1,1])
print(np.dot(x,y))

5


In [ ]:
#21.Find the eigenvalues and eigenvectors of matrix A.
import numpy as np
from numpy.linalg import eig
a = np.array([[2, -12], 
              [1, -5]])
w,v=eig(a)
print(w)
print(v)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
